---
title:"seatrackGLS workflow tutorial"
output:
  html_document:
  date:"2025-11-26"
---

Prepare colony metadata, basic metadata for calibration. Basic metadata must have
logger_id, logger_model, species, colony, deployment_date, retrieval_date. 
Extra metadata can also be provided, but isn't neccesary during the calibration step.

```{r setup}

```

Run `process_folder` in calibration mode. This will export calibration plots and 

```{r calibrate}

all_colony_info <- data.frame(colony = "Halten", col_lat = 64.1716, col_lon = 9.4078)

prepare_calibration(
  import_directory = import_directory,
  metadata = metadata,
  all_colony_info = all_colony_info,
  output_dir = "test"
)

```

Stare at the plots. Use the force.

```{r run_process}
test_dir <- "test/calibration_data"
file_name <- list.files(test_dir)[1]
calibration_data_path <- file.path(test_dir, file_name)
extra_metadata <- data.frame(foo = "bar")
process_positions(
  import_directory = import_directory,
  calibration_data = calibration_data_path,
  all_colony_info = all_colony_info,
  output_dir = "test",
  extra_metadata = extra_metadata
)

```

```{r}
test_output_dir <- "test/processed_positions"
position_file_name <- file_name <- list.files(test_output_dir)[1]
positions <- read.csv(file.path(test_output_dir, position_file_name))
plot_a_map(positions)
```